media_folder: static/assets
public_folder: /assets

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { label: Featured Image, name: thumbnail, widget: image }
  - name: articles
    label: Article
    folder: content/articles
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: published, label: Published, widget: "boolean", default: true }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { label: image, name: image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - file: content/about/index.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
