media_folder: static/assets
public_folder: /assets

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: news
    label: News
    folder: content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: published, label: Published, widget: "boolean", default: true }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { label: image, name: image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: offer
    label: Offer
    folder: content/offer
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { label: image, name: image, widget: image }
      - {
          name: categories,
          label: Categories,
          widget: list,
          field: { label: Category, name: category, widget: string },
        }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - file: content/about/index.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: content/home/index.md
        label: Home
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: image, name: image, widget: image }
          - { label: Body, name: body, widget: markdown }
