media_folder: static/assets/ada
public_folder: /assets

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: news
    label: News
    folder: content/ada/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: published, label: Published, widget: boolean, default: true }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { label: image, name: image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: offer
    label: Offer
    folder: content/ada/offer
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { label: image, name: image, widget: image }
      - {
          name: categories,
          label: Categories,
          widget: list,
          field: { label: Category, name: category, widget: string },
        }
      - { name: body, label: Body, widget: markdown }
  - name: promotions
    label: Promotions
    folder: content/ada/promotions
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: active, label: Active, widget: boolean, default: true }
      - { label: image, name: image, widget: image }
      - {
          name: type,
          label: Type,
          widget: select,
          options: ["newPrice", "percentage"],
          default: "newPrice",
        }
      - { name: oldPrice, label: Old Price, widget: number, valueType: float }
      - { name: newPrice, label: New Price, widget: number, valueType: float }
      - { name: percentage, label: Percentage, widget: number, valueType: int }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: content/ada/about/index.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: content/ada/home/index.md
        label: Home
        name: home
        fields:
          - { label: Title, name: title, widget: string }
          - { label: image, name: image, widget: image }
          - { label: Body, name: body, widget: markdown }
